version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/ethereum-network-partition-test"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "github.com/kurtosis-tech/kurtosis-sdk/api/golang"
